### ISSUE TITLE
Do not bury lithium batteries....

### ISSUE THREAD

**Issue by jhiggason** [anish-natekar/PicoW_Copter_docs#1]
"first using a large resistance to slowly discharge the Lipo completely and slowly and then burrying it"

This is included under the battery section of your docs.  LIPO batteries should not be buried.  Heavy metals from the battery can leach into the ground water table and slowly poisen you and your community.  Lithium batteries need to be disposed of by recycling at a proper facility.  Do not bury batteries, regardless if you have laws or not pertaining to proper disposal of heavy metals.

**Comment by anish-natekar** [comment]
Hey jhiggason, thanks for the information, I had written this procedure because it came with the manual of the battery manufacturer. I agree that Lipo batteries are dangerous but I was not sure about heavy metal (as Lithium is not a heavy metal) poisoning so I did some research. In this article pg 4 [(Article on Lithium batteries)](https://www.intertek.com/uploadedFiles/Intertek/Divisions/Commercial_and_Electrical/Media/PDF/Battery/Environmental-Considerations-for-Lithium-Batteries-White-Paper.pdf) it does mention that Lion batteries have Heavy elements such as Copper, Cobalt, and Nickle (but no mercury, cadmium, and lead) so I am assuming that Lipo batteries might have something similar in them and can cause long term environmental problems. I will update the docs and link this article as an explanation. Thank you for pointing this out and feel free to ask any questions or point out other issues.
